// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLZ3jMnnpRwG_OQExN79KbgUJgJxB-BR4',
    appId: '1:952032975161:web:f3bb247b457b3a9baef0e8',
    messagingSenderId: '952032975161',
    projectId: 'goo-team',
    authDomain: 'goo-team.firebaseapp.com',
    storageBucket: 'goo-team.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg7SqtKBKDwNqLvN9edxcsfovGwHp9DLM',
    appId: '1:952032975161:android:78071788c24969f9aef0e8',
    messagingSenderId: '952032975161',
    projectId: 'goo-team',
    storageBucket: 'goo-team.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5oQbYAY1pB1uHYFzaySFycsxiMA0AA4M',
    appId: '1:952032975161:ios:6f93884efdf166f5aef0e8',
    messagingSenderId: '952032975161',
    projectId: 'goo-team',
    storageBucket: 'goo-team.firebasestorage.app',
    iosBundleId: 'com.gooteam.stream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5oQbYAY1pB1uHYFzaySFycsxiMA0AA4M',
    appId: '1:952032975161:ios:6f93884efdf166f5aef0e8',
    messagingSenderId: '952032975161',
    projectId: 'goo-team',
    storageBucket: 'goo-team.firebasestorage.app',
    iosBundleId: 'com.gooteam.stream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLZ3jMnnpRwG_OQExN79KbgUJgJxB-BR4',
    appId: '1:952032975161:web:f3bb247b457b3a9baef0e8',
    messagingSenderId: '952032975161',
    projectId: 'goo-team',
    authDomain: 'goo-team.firebaseapp.com',
    storageBucket: 'goo-team.firebasestorage.app',
  );
}
